import { Router } from "express";
import { getUser, login, logout, register,verifyOTP } from "../controllers/authController.js";
import { isAuthenticated } from "../middlewares/authentication.js";
const router=Router();
router.post('/register',register);
router.post('/verifyOTP',verifyOTP);
router.post('/login',login);
router.get('/logout', isAuthenticated, logout);
router.get('/me', isAuthenticated, getUser);
export default router;